### ISSUE TITLE
I can't install

### ISSUE THREAD

**Issue by venkatasubash** [darawish/domainbook#1]
Mac is giving me this error "This software needs to be updated. Contact the developer for more information."

thank you

**Comment by linuxjuggler** [comment]
Hey @venkatasubash thanks for reaching out.

Since the last update for macOS 10.14.5 apple required all the apps to be notarized, which is something we are working on right now.

Hopefully, we will release a new version in the next few days which will be fully notarized and fully working.

Once we got it updated we will let you know.

If there is anything else we can do, please let us know.

Our email is: info@darawish.io 

Thanks again and sorry for this inconvenience.

**Comment by venkatasubash** [comment]
Thanks its working

**Comment by linuxjuggler** [comment]
Great news.

Thanks again
