### ISSUE TITLE
Feature Request

### ISSUE THREAD

**Issue by blackforestcode** [darawish/domainbook#2]
A few suggestions:
- Notifications, e. g. 30 days before expiring
- Dark-/Light Theme switcher
- Make the "Total Domains" card clickable

**Comment by linuxjuggler** [comment]
Thanks @blackforestcode for the suggestions.

We can't promise anything yet, but we promise to do our best.

**Comment by blackforestcode** [comment]
You're welcome. I know you'll do your best. :-)

**Comment by linuxjuggler** [comment]
Hey @blackforestcode 

We just released version 1.2.7 which include Dark theme based on your system appearance preferences, so it is not manually set.

![Screen Shot 2019-06-30 at 9 41 05 PM](https://user-images.githubusercontent.com/27624/60400684-f419e380-9b7f-11e9-8ec4-1fa3b1743e06.png)
![Screen Shot 2019-06-30 at 9 41 29 PM](https://user-images.githubusercontent.com/27624/60400685-f4b27a00-9b7f-11e9-8536-ef45e36e9113.png)

I am still looking into the `Notifications` feature and see the best way to implement it. Meanwhile, I have decided not to make the `total count` clickable as it does not add much value since the side menu is always active

**Comment by blackforestcode** [comment]
Great, thanks for the update! 😃

**Comment by linuxjuggler** [comment]
I just released version 1.3.0 which got some new features like:

1. ability to run in the background.
2. notify you about the domains which will expire in the next 30 days, once a day the application will check and inform you.
3. manually check for the updates.

I am still working on adding new features which for sure you will get with each new release. My main focus for the next version is to auto-update the whois information for the domains.

I hope such features will make the app more useful.
Thanks

**Comment by linuxjuggler** [comment]
I'll close this task since I've opened a separate one for making the boxes clickable. https://github.com/darawish/domainbook/issues/5
